import { createContext, useContext, useState, useEffect } from 'react'

const STORAGE_KEY = 'rma_lang'

const ar = {
  // Nav
  nav_home: 'الرئيسية',
  nav_gen: 'المولد',
  nav_bmr: 'BMR',
  nav_pricing: 'الباقات',
  nav_account: 'حسابي',
  nav_login: 'دخول',
  nav_logout: 'خروج',
  nav_remaining: 'الاشتراك متبقي',
  nav_admin: 'الإدارة',
  nav_en: 'English',
  nav_ar: 'العربية',
  // Home
  home_title1: 'RMA',
  home_title2: 'Trainer AI',
  home_desc: 'مدربك الشخصي للفنون القتالية واللياقة — خطط تدريب ذكية مبنية على أهدافك وإمكانياتك',
  home_btn: 'ابدأ التمرين 🏋️',
  home_pricing: 'عرفني على الباقات',
  home_bmr: 'حاسبة السعرات 🔥',
  home_feat1: 'خطط مخصصة',
  home_feat1d: 'حسب هدفك، مستواك، أيامك، ومعداتك',
  home_feat2: 'ذكاء تدريبي',
  home_feat2d: 'منهجية واقعية مستوحاة من RMA',
  home_feat3: 'نتائج حقيقية',
  home_feat3d: 'لا وعود كاذبة — تطور ثابت وآمن',
  home_tagline: 'RMA Trainer AI — فلسفة تدريبية واقعية. لا معجزات، فقط عمل شيق ومنهجية.',
  home_visitors: 'عدد الزوار:',
  // WorkoutForm
  wf_name: 'الاسم',
  wf_name_pl: 'مثال: أحمد',
  wf_age: 'العمر',
  wf_age_pl: 'مثال: 25',
  wf_weight: 'الوزن (كجم)',
  wf_weight_pl: 'مثال: 75',
  wf_height: 'الطول (سم)',
  wf_height_pl: 'مثال: 175',
  wf_goal: 'الهدف',
  wf_level: 'المستوى',
  wf_days: 'أيام التمرين',
  wf_type: 'نوع التمرين',
  wf_equip: 'المعدات المتاحة (اختر كل اللي عندك)',
  wf_equip_none: '(بدون أجهزة — تمارين وزن الجسم)',
  wf_submit: 'توليد الخطة 🥋',
  wf_submit_loading: 'جاري التوليد...',
  wf_error_name: 'الاسم مطلوب',
  wf_error_weight: 'الوزن مطلوب',
  wf_error_height: 'الطول مطلوب',
  wf_error_age: 'العمر مطلوب',
  // Goals
  goal_fat_loss: 'حرق دهون',
  goal_muscle_gain: 'بناء عضلات',
  goal_endurance: 'تحمل قتالي',
  goal_strength: 'قوة',
  goal_general: 'لياقة عامة',
  // Levels
  level_beginner: 'مبتدئ',
  level_intermediate: 'متوسط',
  level_advanced: 'متقدم',
  // Days
  days: 'أيام',
  // Training types
  type_mma: 'MMA',
  type_boxing: 'ملاكمة',
  type_kickboxing: 'كيك بوكس',
  type_bjj: 'جيوجيتسو',
  type_muay_thai: 'مواي تاي',
  type_taekwondo: 'تاي كون دو',
  type_karate: 'كاراتيه',
  type_wrestling: 'مصارعة',
  type_general: 'عام',
  type_gym: 'جيم (معدات كاملة)',
  // Equipment
  equip_dumbbell: 'دمبل',
  equip_barbell: 'بار',
  equip_pullup_bar: 'عقلة',
  equip_bench: 'كرسي/بنش',
  equip_step: 'استيب',
  equip_kettlebell: 'كيتبل',
  equip_resistance_bands: 'باند مقاومة',
  equip_cable: 'كابل',
  equip_gym_machine: 'أجهزة جيم',
  equip_leg_press: 'ليج بريس',
  equip_lat_pulldown: 'لات ب ld',
  equip_smith_machine: 'سميث مشين',
  equip_full_gym: 'جيم متكامل',
  equip_gym_all: 'تحديد الكل',
  // Generator
  gen_title: 'مولد خطط التدريب',
  gen_desc: 'املأ بياناتك واحصل على خطة تدريب ذكية مبنية بالذكاء الاصطناعي',
  wf_injuries: 'الإصابات (اختياري)',
  inj_shoulder: 'الكتف',
  inj_knee: 'الركبة',
  inj_lower_back: 'أسفل الظهر',
  // Result
  res_title: 'خطتك التدريبية',
  res_goal: 'الهدف',
  res_split: 'التقسيمة',
  res_day: 'اليوم',
  res_focus: 'التركيز',
  res_exercises: 'التمارين',
  res_exercise: 'التمرين',
  res_sets: 'مجموعات',
  res_reps: 'تكرارات',
  res_rest: 'راحة',
  res_duration: 'المدة',
  res_min: 'دقيقة',
  res_cardio: '🔥 كارديو:',
  res_nutrition: 'التغذية',
  res_bmr: 'معدل الأيض',
  res_calories: 'السعرات',
  res_protein: 'البروتين',
  res_tips: 'نصائح',
  res_pdf: 'تصدير PDF',
  res_new: 'خطة جديدة',
  res_gen: 'توليد الخطة',
  // Pricing
  pr_title: 'الباقات والأسعار',
  pr_monthly: 'شهرياً',
  pr_once: 'مرة واحدة',
  pr_free: 'مجاني',
  pr_btn: 'ابدأ مجاناً',
  pr_btn_pro: 'اشترك الآن',
  pr_feat_limited: 'توليد 3 خطط/شهر',
  pr_feat_unlimited: 'توليد غير محدود',
  pr_feat_advanced: 'تمارين متقدمة',
  pr_feat_diet: 'نظام غذائي مخصص',
  pr_feat_pdf: 'تصدير PDF',
  pr_feat_videos: 'فيديوهات تمارين يوتيوب',
  pr_feat_profile: 'تعديل البروفايل',
  pr_feat_contact: 'دعم أولوية',
  pr_or: 'أو استخدم كود تفعيل',
  pr_code_pl: 'كود التفعيل',
  pr_activate: 'تفعيل',
  pr_login_req: 'يجب تسجيل الدخول أولاً لتفعيل الكود',
  pr_need_login: 'سجل دخولك',
  pr_need_login2: 'لازم تسجل دخول أولاً.',
  // Login
  li_title: 'تسجيل الدخول',
  li_email: 'البريد الإلكتروني',
  li_password: 'كلمة السر',
  li_btn: 'دخول',
  li_no_account: 'ماعندكش حساب؟',
  li_register: 'سجل',
  li_reg_title: 'إنشاء حساب',
  li_name: 'الاسم',
  li_name_pl: 'اسمك',
  li_confirm: 'تأكيد كلمة السر',
  li_btn_reg: 'إنشاء حساب',
  li_have_account: 'عندك حساب؟',
  li_login: 'سجل دخول',
  li_error_email: 'البريد الإلكتروني مطلوب',
  li_error_pass: 'كلمة السر مطلوبة (6 أحرف على الأقل)',
  li_error_match: 'كلمة السر غير متطابقة',
  li_error_name_req: 'الاسم مطلوب',
  li_sub_register: 'اشترك للوصول الكامل',
  li_sub_login: 'ادخل لحسابك',
  li_success: 'تم بنجاح!',
  fp_title: 'نسيت كلمة السر',
  fp_subtitle: 'استعد حسابك',
  fp_enter_email: 'أدخل بريدك الإلكتروني لإرسال كود التحقق',
  fp_send_code: 'إرسال كود التحقق',
  fp_your_code: 'كود التحقق الخاص بك',
  fp_code_expiry: 'صالح لمدة ١٠ دقائق',
  fp_enter_code: 'أدخل كود التحقق (٦ أرقام)',
  fp_verify: 'تحقق',
  fp_new_password: 'أدخل كلمة السر الجديدة (٦ أحرف على الأقل)',
  fp_reset_btn: 'تغيير كلمة السر',
  fp_back: '→ الرجوع لتسجيل الدخول',
  fp_email_not_found: 'البريد غير مسجل',
  fp_code_sent: 'تم إنشاء كود التحقق',
  fp_invalid_code: 'كود التحقق غلط أو منتهي الصلاحية',
  fp_password_short: 'كلمة السر قصيرة (٦ أحرف على الأقل)',
  fp_success: 'تم تغيير كلمة السر بنجاح!',
  fp_error: 'حصل خطأ، حاول تاني',
  // Payment
  pay_title: 'اشتراك Pro',
  pay_instructions: 'تعليمات الدفع',
  pay_price: 'المبلغ: 1000 جنيه مصري — مرة واحدة فقط',
  pay_wallet: 'محفظة فودافون كاش',
  pay_number: 'الرقم:',
  pay_steps: 'خطوات الدفع:',
  pay_step1: '1. افتح محفظة فودافون كاش',
  pay_step2: '2. ارسل 1000 جنيه إلى الرقم',
  pay_step3: '3. احتفظ برقم العملية',
  pay_step4: '4. اضغط "تأكيد الدفع" بالأسفل',
  pay_note: 'بعد التأكيد، سيتم مراجعة طلبك من الإدارة وتفعيل الاشتراك خلال 24 ساعة.',
  pay_confirm: 'تأكيد الدفع',
  pay_contact: 'للتواصل',
  pay_whatsapp: 'واتساب:',
  // Dashboard
  dash_title: 'لوحة المشترك',
  dash_pro: 'Pro',
  dash_days: 'متبقي',
  dash_day: 'يوم',
  dash_profile: 'البيانات الشخصية',
  dash_phone: 'رقم الهاتف',
  dash_goal: 'هدفك التدريبي',
  dash_save: 'حفظ التعديلات',
  dash_saved: 'تم الحفظ ✓',
  dash_videos: 'فيديوهات التمارين',
  dash_no_videos: 'ما في فيديوهات مضافة من الإدارة',
  dash_contact: 'التواصل مع المدرب',
  dash_pending_title: 'طلبك قيد المراجعة',
  dash_pending_desc: 'إنتظر موافقة الإدارة على طلب اشتراكك في Pro. هتوصلك رسالة قريب.',
  dash_pending_home: 'الرئيسية',
  dash_rejected_title: 'تم رفض الطلب',
  dash_rejected_desc: 'للأسف لم يتم الموافقة على طلبك. تواصل مع الإدارة للمزيد.',
  dash_revoked_title: 'تم إلغاء الاشتراك',
  dash_revoked_desc: 'تم إلغاء اشتراكك في Pro. تواصل مع الإدارة للمزيد.',
  dash_revoked_contact: 'للتواصل:',
  // Admin
  admin_login_title: 'دخول الإدارة',
  admin_login_btn: 'دخول',
  admin_title: 'لوحة الإدارة',
  admin_stats: 'إحصائيات سريعة',
  admin_reqs: 'الطلبات',
  admin_plan: 'خطط مخصصة',
  admin_add_plan: 'إضافة خطة',
  admin_edit_plan: 'تعديل',
  admin_delete_plan: 'مسح',
  admin_pricing: 'الباقات',
  admin_save_pricing: 'نشر الباقات',
  admin_login_error: 'كلمة سر خطأ',
  admin_login_subtitle: 'فقط للمشرفين',
  admin_subtitle: 'تحكم بكل شيء',
  admin_logout: 'خروج',
  // Admin tabs
  tab_settings: 'الإعدادات',
  tab_dashboard: 'الإحصائيات',
  tab_requests: 'الطلبات',
  tab_codes: 'الأكواد',
  tab_videos: 'فيديوهات',
  tab_plans: 'خطط',
  tab_pricing: 'باقات',
  tab_ads: 'إعلانات',
  tab_users: 'المستخدمين',
  // Requests
  req_pending: 'معلق',
  req_approved: 'مقبول',
  req_rejected: 'مرفوض',
  req_approve: 'موافقة',
  req_reject: 'رفض',
  req_revoke: 'إلغاء الاشتراك',
  req_delete: 'حذف',
  req_no_requests: 'ما في طلبات',
  // Codes
  code_title: 'إدارة الأكواد',
  code_serial: 'كود سيريال',
  code_generate: 'توليد {count} كود',
  code_count: 'عدد الأكواد',
  code_add: 'إضافة',
  code_used: 'مستخدم',
  code_unused: 'غير مستخدم',
  code_used_by: 'مستخدم من',
  code_no_codes: 'ما في أكواد',
  // Videos
  vid_add: 'إضافة',
  vid_pl: 'رابط يوتيوب',
  vid_no_videos: 'ما في فيديوهات مضافة',
  vid_delete: 'مسح',
  vid_clear: 'مسح الكل',
  // Active Pro Users
  active_title: 'المشتركين النشطين',
  active_email: 'البريد',
  active_code: 'الكود',
  active_expires: 'ينتهي',
  active_days: 'أيام متبقية',
  active_revoke: 'إلغاء الاشتراك',
  active_no_users: 'ما في مشتركين',
  // Dashboard stats
  stats_total_codes: 'إجمالي الأكواد',
  stats_used_codes: 'المفعلة من الأكواد',
  stats_available_codes: 'المتبقية من الأكواد',
  stats_videos: 'الفيديوهات',
  stats_pending_requests: 'طلبات معلقة',
  stats_custom_plans: 'خطط مخصصة',
  // Codes management
  code_length: 'طول الكود',
  code_search: 'بحث عن كود...',
  code_total: 'إجمالي',
  code_used_label: 'مفعل',
  code_available_label: 'متبقي',
  code_new_badge: 'جديد',
  code_active_badge: 'مفعل ✓',
  code_copy: 'نسخ',
  code_copied: 'تم النسخ ✓',
  code_no_results: 'ما في نتائج بحث',
  code_no_codes_hint: 'ما في أكواد. اضغط توليد.',
  code_clear_all: '✕ مسح الكل',
  code_clear_unused: 'مسح الغير مفعلة',
  code_export_csv: 'CSV',
  code_export_sql: 'SQL',
  code_export_json: 'JSON للنشر',
  // Confirm dialogs
  confirm_revoke_user: 'إلغاء اشتراك {email}؟',
  confirm_delete_request: 'مسح هذا الطلب نهائياً؟',
  confirm_delete_plan: 'تحذف الخطة؟',
  confirm_delete_all_codes: 'مسح كل الأكواد نهائياً؟',
  confirm_clear_unused: 'مسح الأكواد غير المفعلة؟',
  confirm_reset_pricing: 'رجوع للإعدادات الافتراضية؟',
  confirm_publish: 'نشر التعديلات لكل المستخدمين؟',
  // Plans management
  plan_no_plans: 'ما في خطط مخصصة. اضغط إضافة.',
  plan_new_title: 'خطة جديدة',
  plan_edit_title: 'تعديل خطة',
  plan_back: 'رجوع',
  plan_name_label: 'اسم الخطة',
  plan_name_pl: 'مثال: خطة متقدم MMA',
  plan_goal_label: 'الهدف',
  plan_goal_pl: 'حرق دهون / قوة',
  plan_level_label: 'المستوى',
  plan_level_pl: 'مبتدئ / متوسط',
  plan_delete_day: 'حذف اليوم',
  plan_focus_label: 'تركيز اليوم',
  plan_focus_pl: 'صدر + كتف + ترايسبس',
  plan_exercise_name_pl: 'اسم التمرين',
  plan_add_exercise: '+ إضافة تمرين',
  plan_add_day: '+ إضافة يوم',
  plan_save_edit: 'حفظ التعديلات',
  plan_save_new: 'حفظ الخطة',
  plan_default_day_1: 'اليوم 1',
  plan_default_day_n: 'اليوم {n}',
  plan_more_days: '+{count} أيام أخرى',
  // Pricing editor
  pricing_edit_title: 'تعديل الباقات',
  pricing_auto_save: 'التعديلات بتنحفظ تلقائياً ✓',
  pricing_popular: 'الأكثر رواجاً',
  pricing_delete: '✕ مسح',
  pricing_plan_name: 'اسم الباقة',
  pricing_price: 'السعر',
  pricing_expires: 'ينتهي',
  pricing_currency: 'العملة',
  pricing_period: 'المدة',
  pricing_btn_text: 'نص الزر',
  pricing_btn_link: 'رابط الزر (مثال: /payment)',
  pricing_features: 'المميزات',
  pricing_new_feature: 'ميزة جديدة',
  pricing_new_plan_name: 'باقة جديدة',
  pricing_default_currency: 'ريال',
  pricing_default_period: '/شهر',
  pricing_feature_1: 'ميزة 1',
  pricing_feature_2: 'ميزة 2',
  pricing_default_btn: 'اشترك',
  pricing_add_feature: '+ إضافة ميزة',
  pricing_add_plan: '+ إضافة باقة جديدة',
  pricing_reset_default: 'استعادة الإعدادات الافتراضية',
  pricing_publish: '📡 نشر التعديلات',
  publishing: 'جاري النشر...',
  publish_success: '✓ تم النشر للجميع',
  publish_error: '✕ فشل النشر — تأكد من إعدادات Supabase',
  publish_hint: 'ينشر التعديلات لكل المستخدمين',
  // Requests management
  req_refresh: '⟳ تحديث',
  req_email_pl: 'إيميل المستخدم',
  req_add_manual: '+ إضافة طلب يدوي',
  req_status_revoked: 'ملغي',
  req_revoked_note: 'تم الإلغاء',
  // Settings
  settings_title: 'حماية لوحة الإدارة',
  settings_pass_info: 'الباسوورد الافتراضي: {pass}',
  settings_change_info: 'لتغييره، افتح ملف {file} وغير قيمة {var}',
  settings_quick_links: 'روابط سريعة',
  settings_route_home: 'الرئيسية',
  settings_route_gen: 'مولد الخطط',
  settings_route_pricing: 'الباقات + تفعيل الكود',
  settings_route_login: 'تسجيل الدخول',
  settings_route_admin: 'دخول المشرفين',
  settings_route_panel: 'لوحة الإدارة',
  settings_publish_info_title: '📢 نشر الأكواد للمستخدمين',
  settings_publish_step1: '1. في تبويب "أكواد التفعيل" اضغط {btn}',
  settings_publish_step2: '2. حط الملف {file} في مجلد {folder}',
  settings_publish_step3: '3. المستخدمين يدخلوا الكود من /pricing',
  settings_publish_step4: '4. أو شغّل SQL حق Supabase عشان قاعدة البيانات',
  // Revoke page
  rev_title: 'إلغاء الاشتراك',
  rev_subtitle: 'إلغاء اشتراك Pro لأي مستخدم',
  rev_pass: 'كلمة سر الإدارة',
  rev_confirm: 'تأكيد الدخول',
  rev_enter: 'دخول',
  rev_email: 'البريد الإلكتروني',
  rev_revoke_title: 'إلغاء اشتراك Pro',
  rev_btn: 'إلغاء الاشتراك',
  rev_loading: 'جاري الإلغاء...',
  rev_another: 'إلغاء اشتراك آخر',
  rev_error_pass: 'كلمة سر خطأ',
  rev_error_email: 'ادخل الإيميل',
  rev_success: '✓ تم إلغاء اشتراك {email} بنجاح',
  rev_error_revoke: '✕ فشل إلغاء الاشتراك — حاول مرة أخرى',
  // BMR
  bmr_title: 'حاسبة BMR و TDEE',
  bmr_desc: 'معدل الأيض الأساسي والسعرات حسب نشاطك',
  bmr_gender: 'الجنس',
  bmr_male: 'ذكر',
  bmr_female: 'أنثى',
  bmr_age: 'السن',
  bmr_age_pl: 'مثال: 25',
  bmr_weight: 'الوزن (كجم)',
  bmr_weight_pl: 'مثال: 75',
  bmr_height: 'الطول (سم)',
  bmr_height_pl: 'مثال: 175',
  bmr_activity: 'مستوى النشاط',
  bmr_bf: 'نسبة الدهون (اختياري — لنتيجة أدق)',
  bmr_bf_pl: 'مثال: 15',
  bmr_btn: 'احسب 🔥',
  bmr_results: 'النتائج',
  bmr_method: 'الطريقة المستخدمة:',
  bmr_lbm: 'كتلة الجسم النحيل (LBM):',
  bmr_steps: 'شرح خطوات الحساب',
  bmr_step1: '1. المعادلة:',
  bmr_step2: '2. LBM =',
  bmr_step3: '3. معامل النشاط:',
  bmr_step4: '4. TDEE =',
  bmr_fat_loss: '🔥 لخسارة الوزن',
  bmr_muscle_gain: '💪 لبناء العضلات',
  bmr_deficit15: 'عجز 15%:',
  bmr_deficit20: 'عجز 20%:',
  bmr_surplus10: 'فائض 10%:',
  bmr_surplus15: 'فائض 15%:',
  // Activity labels
  act_sedentary: 'خامل (بدون تمارين)',
  act_light: 'خفيف (1-3 أيام/أسبوع)',
  act_moderate: 'معتدل (3-5 أيام/أسبوع)',
  act_very: 'نشط (6-7 أيام/أسبوع)',
  act_extreme: 'شديد جداً (مرتين يومياً)',
  // PDF
  pdf_title: 'خطة تدريب RMA',
  pdf_goal: 'الهدف:',
  pdf_split: 'التقسيمة:',
  pdf_type: 'نوع التمرين:',
  pdf_exercise: 'التمرين',
  pdf_sets: 'مجموعات',
  pdf_reps: 'تكرارات',
  pdf_rest: 'راحة',
  pdf_duration: 'مدة',
  pdf_cardio: '🔥 كارديو:',
  pdf_nutrition: 'التغذية',
  pdf_bmr: 'معدل الأيض',
  pdf_calories: 'السعرات',
  pdf_protein: 'البروتين',
  pdf_tips: 'نصائح',
  pdf_generated: 'تم التوليد بواسطة RMA Trainer AI',
  // Footer
  footer_rights: 'جميع الحقوق محفوظة',
  // Auth
  auth_signout: 'تسجيل الخروج',
  // Errors
  err_required: 'مطلوب',
  err_invalid: 'غير صحيح',
  err_network: 'خطأ في الشبكة',
  // Result extra
  res_no_plan: 'ما في خطة للعرض. ارجع واطلع على خطة جديدة.',
  res_back: '← رجوع',
  res_back_gen: 'رجّع للمولد',
  res_for: 'خاصة بـ',
  res_personal: 'حساباتك الشخصية',
  ads_label: 'إعلان',
  ads_unnamed: 'بدون اسم',
  ads_title: 'الإعلانات',
  ads_add: '+ إضافة إعلان',
  ads_no_ads: 'ما في إعلانات',
  ads_name: 'اسم الإعلان',
  ads_name_pl: 'مثال: إعلان متجر',
  ads_type: 'النوع',
  ads_type_banner: 'بانر',
  ads_type_video: 'فيديو',
  ads_image_url: 'رابط الصورة',
  ads_video_url: 'رابط الفيديو',
  ads_link_url: 'رابط الوجهة',
  ads_position: 'المكان',
  ads_pos_top: 'أعلى',
  ads_pos_middle: 'وسط',
  ads_pos_bottom: 'أسفل',
  ads_pos_left: 'يسار',
  ads_pos_right: 'يمين',
  ads_active: 'نشط',
  ads_save: 'حفظ',
  ads_edit: 'تعديل',
  ads_new: 'إعلان جديد',
  ads_link: 'الرابط',
  ads_order: 'الترتيب',
  ads_width: 'العرض (مثل 300px)',
  ads_height: 'الارتفاع (مثل 250px)',
  confirm_delete_ad: 'مسح الإعلان؟',
  users_count_label: 'مستخدم',
  users_no_users: 'ما في مستخدمين',
  users_registered_at: 'التاريخ',
  req_months: 'شهر',
  tab_notifications: 'الإشعارات',
  notif_title: 'إرسال إشعار',
  notif_message_pl: 'اكتب الرسالة...',
  notif_target_all: 'جميع المستخدمين',
  notif_target_specific: 'مستخدم محدد',
  notif_send: 'إرسال الإشعار',
  notif_sent: '✓ تم الإرسال',
  notif_no_notifs: 'ما في إشعارات',
  notif_history: 'الإشعارات السابقة',
  notif_email_pl: 'البريد الإلكتروني للمستخدم',
  notif_preview: 'معاينة الإشعار',
  notif_sent_at: 'أُرسل',
  notif_schedule_label: 'جدولة (توقيت محدد)',
  notif_scheduled_time: 'ميعاد الظهور',
  notif_pending: 'قيد الانتظار',
}

const en = {
  nav_home: 'Home',
  nav_gen: 'Generator',
  nav_bmr: 'BMR',
  nav_pricing: 'Pricing',
  nav_account: 'Dashboard',
  nav_login: 'Login',
  nav_logout: 'Logout',
  nav_remaining: 'Pro remaining',
  nav_admin: 'Admin',
  nav_en: 'English',
  nav_ar: 'العربية',
  home_title1: 'RMA',
  home_title2: 'Trainer AI',
  home_desc: 'Your personal martial arts & fitness trainer — smart workout plans based on your goals and equipment',
  home_btn: 'Start Training 🏋️',
  home_pricing: 'View Pricing',
  home_bmr: 'BMR Calculator 🔥',
  home_feat1: 'Custom Plans',
  home_feat1d: 'Based on your goal, level, schedule & gear',
  home_feat2: 'AI Powered',
  home_feat2d: 'Realistic methodology inspired by RMA',
  home_feat3: 'Real Results',
  home_feat3d: 'No false promises — steady, safe progress',
  home_tagline: 'RMA Trainer AI — a realistic training philosophy. No miracles, just solid work.',
  home_visitors: 'Visitors:',
  wf_name: 'Name',
  wf_name_pl: 'e.g. Ahmed',
  wf_age: 'Age',
  wf_age_pl: 'e.g. 25',
  wf_weight: 'Weight (kg)',
  wf_weight_pl: 'e.g. 75',
  wf_height: 'Height (cm)',
  wf_height_pl: 'e.g. 175',
  wf_goal: 'Goal',
  wf_level: 'Level',
  wf_days: 'Training Days',
  wf_type: 'Training Type',
  wf_equip: 'Available Equipment (select all you have)',
  wf_equip_none: '(No equipment — bodyweight exercises)',
  wf_submit: 'Generate Plan 🥋',
  wf_submit_loading: 'Generating...',
  wf_error_name: 'Name is required',
  wf_error_weight: 'Weight is required',
  wf_error_height: 'Height is required',
  wf_error_age: 'Age is required',
  goal_fat_loss: 'Fat Loss',
  goal_muscle_gain: 'Muscle Gain',
  goal_endurance: 'Combat Endurance',
  goal_strength: 'Strength',
  goal_general: 'General Fitness',
  level_beginner: 'Beginner',
  level_intermediate: 'Intermediate',
  level_advanced: 'Advanced',
  days: 'days',
  type_mma: 'MMA',
  type_boxing: 'Boxing',
  type_kickboxing: 'Kickboxing',
  type_bjj: 'BJJ',
  type_muay_thai: 'Muay Thai',
  type_taekwondo: 'Taekwondo',
  type_karate: 'Karate',
  type_wrestling: 'Wrestling',
  type_general: 'General',
  type_gym: 'Gym (Full Equipment)',
  equip_dumbbell: 'Dumbbell',
  equip_barbell: 'Barbell',
  equip_pullup_bar: 'Pull-up Bar',
  equip_bench: 'Bench/Chair',
  equip_step: 'Step',
  equip_kettlebell: 'Kettlebell',
  equip_resistance_bands: 'Resistance Bands',
  equip_cable: 'Cable',
  equip_gym_machine: 'Gym Machines',
  equip_leg_press: 'Leg Press',
  equip_lat_pulldown: 'Lat Pulldown',
  equip_smith_machine: 'Smith Machine',
  equip_full_gym: 'Full Gym',
  equip_gym_all: 'Select All',
  gen_title: 'Workout Plan Generator',
  gen_desc: 'Fill in your details and get an AI-powered smart training plan',
  wf_injuries: 'Injuries (optional)',
  inj_shoulder: 'Shoulder',
  inj_knee: 'Knee',
  inj_lower_back: 'Lower Back',
  res_title: 'Your Training Plan',
  res_goal: 'Goal',
  res_split: 'Split',
  res_day: 'Day',
  res_focus: 'Focus',
  res_exercises: 'Exercises',
  res_exercise: 'Exercise',
  res_sets: 'Sets',
  res_reps: 'Reps',
  res_rest: 'Rest',
  res_duration: 'Duration',
  res_min: 'min',
  res_cardio: '🔥 Cardio:',
  res_nutrition: 'Nutrition',
  res_bmr: 'BMR',
  res_calories: 'Calories',
  res_protein: 'Protein',
  res_tips: 'Tips',
  res_pdf: 'Export PDF',
  res_new: 'New Plan',
  res_gen: 'Generate Plan',
  pr_title: 'Pricing Plans',
  pr_monthly: 'per month',
  pr_once: 'one-time',
  pr_free: 'Free',
  pr_btn: 'Start Free',
  pr_btn_pro: 'Subscribe Now',
  pr_feat_limited: '3 plans/month',
  pr_feat_unlimited: 'Unlimited plans',
  pr_feat_advanced: 'Advanced exercises',
  pr_feat_diet: 'Custom nutrition plan',
  pr_feat_pdf: 'PDF export',
  pr_feat_videos: 'YouTube workout videos',
  pr_feat_profile: 'Profile editing',
  pr_feat_contact: 'Priority support',
  pr_or: 'Or use activation code',
  pr_code_pl: 'Activation code',
  pr_activate: 'Activate',
  pr_login_req: 'You must log in first to activate a code',
  pr_need_login: 'Login',
  pr_need_login2: 'You need to login first.',
  li_title: 'Login',
  li_email: 'Email',
  li_password: 'Password',
  li_btn: 'Login',
  li_no_account: "Don't have an account?",
  li_register: 'Register',
  li_reg_title: 'Create Account',
  li_name: 'Name',
  li_name_pl: 'Your name',
  li_confirm: 'Confirm Password',
  li_btn_reg: 'Create Account',
  li_have_account: 'Already have an account?',
  li_login: 'Login',
  li_error_email: 'Email is required',
  li_error_pass: 'Password is required (min 6 chars)',
  li_error_match: 'Passwords do not match',
  li_error_name_req: 'Name is required',
  li_sub_register: 'Register for full access',
  li_sub_login: 'Login to your account',
  li_success: 'Success!',
  fp_title: 'Forgot Password',
  fp_subtitle: 'Recover your account',
  fp_enter_email: 'Enter your email to receive a verification code',
  fp_send_code: 'Send Code',
  fp_your_code: 'Your verification code',
  fp_code_expiry: 'Valid for 10 minutes',
  fp_enter_code: 'Enter 6-digit code',
  fp_verify: 'Verify',
  fp_new_password: 'Enter new password (min 6 chars)',
  fp_reset_btn: 'Change Password',
  fp_back: '← Back to Login',
  fp_email_not_found: 'Email not registered',
  fp_code_sent: 'Verification code created',
  fp_invalid_code: 'Invalid or expired code',
  fp_password_short: 'Password too short (min 6 chars)',
  fp_success: 'Password changed successfully!',
  fp_error: 'Something went wrong, try again',
  pay_title: 'Pro Subscription',
  pay_instructions: 'Payment Instructions',
  pay_price: 'Amount: 1000 EGP — one-time payment',
  pay_wallet: 'Vodafone Cash',
  pay_number: 'Number:',
  pay_steps: 'Steps:',
  pay_step1: '1. Open Vodafone Cash wallet',
  pay_step2: '2. Send 1000 EGP to the number',
  pay_step3: '3. Keep the transaction ID',
  pay_step4: '4. Click "Confirm Payment" below',
  pay_note: 'After confirmation, your request will be reviewed and activated within 24 hours.',
  pay_confirm: 'Confirm Payment',
  pay_contact: 'Contact',
  pay_whatsapp: 'WhatsApp:',
  dash_title: 'Dashboard',
  dash_pro: 'Pro',
  dash_days: 'Remaining',
  dash_day: 'day(s)',
  dash_profile: 'Personal Info',
  dash_phone: 'Phone',
  dash_goal: 'Your Training Goal',
  dash_save: 'Save Changes',
  dash_saved: 'Saved ✓',
  dash_videos: 'Workout Videos',
  dash_no_videos: 'No videos added by admin yet',
  dash_contact: 'Contact Coach',
  dash_pending_title: 'Request Under Review',
  dash_pending_desc: 'Wait for admin approval of your Pro subscription. You will be notified soon.',
  dash_pending_home: 'Home',
  dash_rejected_title: 'Request Rejected',
  dash_rejected_desc: 'Unfortunately your request was rejected. Contact admin for details.',
  dash_revoked_title: 'Subscription Cancelled',
  dash_revoked_desc: 'Your Pro subscription has been cancelled. Contact admin for details.',
  dash_revoked_contact: 'Contact:',
  admin_login_title: 'Admin Login',
  admin_login_btn: 'Login',
  admin_title: 'Admin Panel',
  admin_stats: 'Quick Stats',
  admin_reqs: 'Requests',
  admin_plan: 'Custom Plans',
  admin_add_plan: 'Add Plan',
  admin_edit_plan: 'Edit',
  admin_delete_plan: 'Delete',
  admin_pricing: 'Pricing',
  admin_save_pricing: 'Publish Plans',
  admin_login_error: 'Wrong password',
  admin_login_subtitle: 'Admins only',
  admin_subtitle: 'Control everything',
  admin_logout: 'Logout',
  tab_dashboard: 'Dashboard',
  tab_requests: 'Requests',
  tab_codes: 'Codes',
  tab_videos: 'Videos',
  tab_plans: 'Plans',
  tab_pricing: 'Pricing',
  tab_ads: 'Ads',
  tab_users: 'Users',
  tab_settings: 'Settings',
  // Dashboard stats
  stats_total_codes: 'Total Codes',
  stats_used_codes: 'Codes Used',
  stats_available_codes: 'Codes Available',
  stats_videos: 'Videos',
  stats_pending_requests: 'Pending Requests',
  stats_custom_plans: 'Custom Plans',
  // Codes management
  code_length: 'Code Length',
  code_search: 'Search code...',
  code_total: 'Total',
  code_used_label: 'Used',
  code_available_label: 'Available',
  code_new_badge: 'New',
  code_active_badge: 'Activated ✓',
  code_copy: 'Copy',
  code_copied: 'Copied ✓',
  code_no_results: 'No results',
  code_no_codes_hint: 'No codes. Click generate.',
  code_clear_all: '✕ Clear All',
  code_clear_unused: 'Clear Unused',
  code_export_csv: 'CSV',
  code_export_sql: 'SQL',
  code_export_json: 'JSON for Publish',
  // Confirm dialogs
  confirm_revoke_user: 'Revoke {email} subscription?',
  confirm_delete_request: 'Delete this request permanently?',
  confirm_delete_plan: 'Delete the plan?',
  confirm_delete_all_codes: 'Delete all codes permanently?',
  confirm_clear_unused: 'Clear unused codes?',
  confirm_reset_pricing: 'Reset to default settings?',
  confirm_publish: 'Publish changes to all users?',
  // Plans management
  plan_no_plans: 'No custom plans. Click add.',
  plan_new_title: 'New Plan',
  plan_edit_title: 'Edit Plan',
  plan_back: 'Back',
  plan_name_label: 'Plan Name',
  plan_name_pl: 'e.g. Advanced MMA Plan',
  plan_goal_label: 'Goal',
  plan_goal_pl: 'Fat Loss / Strength',
  plan_level_label: 'Level',
  plan_level_pl: 'Beginner / Intermediate',
  plan_delete_day: 'Delete Day',
  plan_focus_label: 'Day Focus',
  plan_focus_pl: 'Chest + Shoulders + Triceps',
  plan_exercise_name_pl: 'Exercise name',
  plan_add_exercise: '+ Add Exercise',
  plan_add_day: '+ Add Day',
  plan_save_edit: 'Save Changes',
  plan_save_new: 'Save Plan',
  plan_default_day_1: 'Day 1',
  plan_default_day_n: 'Day {n}',
  plan_more_days: '+{count} more days',
  // Pricing editor
  pricing_edit_title: 'Edit Pricing Plans',
  pricing_auto_save: 'Auto-save ✓',
  pricing_popular: 'Most Popular',
  pricing_delete: '✕ Delete',
  pricing_plan_name: 'Plan Name',
  pricing_price: 'Price',
  pricing_expires: 'Expires',
  pricing_currency: 'Currency',
  pricing_period: 'Period',
  pricing_btn_text: 'Button Text',
  pricing_btn_link: 'Button Link (e.g. /payment)',
  pricing_features: 'Features',
  pricing_new_feature: 'New Feature',
  pricing_new_plan_name: 'New Plan',
  pricing_default_currency: 'SAR',
  pricing_default_period: '/month',
  pricing_feature_1: 'Feature 1',
  pricing_feature_2: 'Feature 2',
  pricing_default_btn: 'Subscribe',
  pricing_add_feature: '+ Add Feature',
  pricing_add_plan: '+ Add New Plan',
  pricing_reset_default: 'Reset to Default',
  pricing_publish: '📡 Publish Changes',
  publishing: 'Publishing...',
  publish_success: '✓ Published',
  publish_error: '✕ Publish failed — check Supabase settings',
  publish_hint: 'Publishes changes to all users',
  // Requests management
  req_refresh: '⟳ Refresh',
  req_email_pl: 'User email',
  req_add_manual: '+ Add Manual Request',
  req_status_revoked: 'Revoked',
  req_revoked_note: 'Revoked',
  // Settings
  settings_title: 'Admin Panel Security',
  settings_pass_info: 'Default password: {pass}',
  settings_change_info: 'To change, open {file} and change {var}',
  settings_quick_links: 'Quick Links',
  settings_route_home: 'Home',
  settings_route_gen: 'Plan Generator',
  settings_route_pricing: 'Pricing + Code Activation',
  settings_route_login: 'Login',
  settings_route_admin: 'Admin Login',
  settings_route_panel: 'Admin Panel',
  settings_publish_info_title: '📢 Publishing Codes',
  settings_publish_step1: '1. In "Codes" tab click {btn}',
  settings_publish_step2: '2. Put {file} in the {folder} folder',
  settings_publish_step3: '3. Users enter codes at /pricing',
  settings_publish_step4: '4. Or run SQL for Supabase database',
  req_pending: 'Pending',
  req_approved: 'Approved',
  req_rejected: 'Rejected',
  req_approve: 'Approve',
  req_reject: 'Reject',
  req_revoke: 'Revoke',
  req_delete: 'Delete',
  req_no_requests: 'No requests',
  code_title: 'Code Management',
  code_serial: 'Serial Code',
  code_generate: 'Generate {count} Codes',
  code_count: 'Count',
  code_add: 'Add',
  code_used: 'Used',
  code_unused: 'Unused',
  code_used_by: 'Used by',
  code_no_codes: 'No codes',
  vid_add: 'Add',
  vid_pl: 'YouTube URL',
  vid_no_videos: 'No videos added',
  vid_delete: 'Delete',
  vid_clear: 'Clear All',
  active_title: 'Active Pro Users',
  active_email: 'Email',
  active_code: 'Code',
  active_expires: 'Expires',
  active_days: 'Days Left',
  active_revoke: 'Revoke',
  active_no_users: 'No active users',
  rev_title: 'Revoke Subscription',
  rev_subtitle: 'Cancel Pro subscription for any user',
  rev_pass: 'Admin Password',
  rev_confirm: 'Confirm Login',
  rev_enter: 'Enter',
  rev_email: 'Email',
  rev_revoke_title: 'Revoke Pro Subscription',
  rev_btn: 'Revoke Subscription',
  rev_loading: 'Revoking...',
  rev_another: 'Revoke Another',
  rev_error_pass: 'Wrong password',
  rev_error_email: 'Enter email',
  rev_success: '✓ Subscription for {email} revoked successfully',
  rev_error_revoke: '✕ Failed to revoke — try again',
  bmr_title: 'BMR & TDEE Calculator',
  bmr_desc: 'Basal Metabolic Rate & calories based on your activity',
  bmr_gender: 'Gender',
  bmr_male: 'Male',
  bmr_female: 'Female',
  bmr_age: 'Age',
  bmr_age_pl: 'e.g. 25',
  bmr_weight: 'Weight (kg)',
  bmr_weight_pl: 'e.g. 75',
  bmr_height: 'Height (cm)',
  bmr_height_pl: 'e.g. 175',
  bmr_activity: 'Activity Level',
  bmr_bf: 'Body Fat % (optional — for better accuracy)',
  bmr_bf_pl: 'e.g. 15',
  bmr_btn: 'Calculate 🔥',
  bmr_results: 'Results',
  bmr_method: 'Method used:',
  bmr_lbm: 'Lean Body Mass (LBM):',
  bmr_steps: 'Calculation Steps',
  bmr_step1: '1. Equation:',
  bmr_step2: '2. LBM =',
  bmr_step3: '3. Activity factor:',
  bmr_step4: '4. TDEE =',
  bmr_fat_loss: '🔥 For Fat Loss',
  bmr_muscle_gain: '💪 For Muscle Gain',
  bmr_deficit15: 'Deficit 15%:',
  bmr_deficit20: 'Deficit 20%:',
  bmr_surplus10: 'Surplus 10%:',
  bmr_surplus15: 'Surplus 15%:',
  act_sedentary: 'Sedentary (no exercise)',
  act_light: 'Light (1-3 days/week)',
  act_moderate: 'Moderate (3-5 days/week)',
  act_very: 'Very Active (6-7 days/week)',
  act_extreme: 'Extreme (twice daily)',
  pdf_title: 'RMA Training Plan',
  pdf_goal: 'Goal:',
  pdf_split: 'Split:',
  pdf_type: 'Type:',
  pdf_exercise: 'Exercise',
  pdf_sets: 'Sets',
  pdf_reps: 'Reps',
  pdf_rest: 'Rest',
  pdf_duration: 'Duration',
  pdf_cardio: '🔥 Cardio:',
  pdf_nutrition: 'Nutrition',
  pdf_bmr: 'BMR',
  pdf_calories: 'Calories',
  pdf_protein: 'Protein',
  pdf_tips: 'Tips',
  pdf_generated: 'Generated by RMA Trainer AI',
  footer_rights: 'All rights reserved',
  auth_signout: 'Logout',
  err_required: 'Required',
  err_invalid: 'Invalid',
  err_network: 'Network error',
  res_no_plan: 'No plan to display. Go back and generate a new one.',
  res_back: '← Back',
  res_back_gen: 'Back to Generator',
  res_for: 'For',
  res_personal: 'Your Personal Stats',
  ads_label: 'Ads',
  ads_unnamed: 'Unnamed',
  ads_title: 'Ads',
  ads_add: '+ Add Ad',
  ads_no_ads: 'No ads',
  ads_name: 'Ad Name',
  ads_name_pl: 'e.g. Store Ad',
  ads_type: 'Type',
  ads_type_banner: 'Banner',
  ads_type_video: 'Video',
  ads_image_url: 'Image URL',
  ads_video_url: 'Video URL (YouTube embed)',
  ads_link_url: 'Link URL',
  ads_position: 'Position',
  ads_pos_top: 'Top',
  ads_pos_middle: 'Middle',
  ads_pos_bottom: 'Bottom',
  ads_pos_left: 'Left',
  ads_pos_right: 'Right',
  ads_active: 'Active',
  ads_save: 'Save',
  ads_edit: 'Edit',
  ads_new: 'New Ad',
  ads_link: 'Link',
  ads_order: 'Order',
  ads_width: 'Width (e.g. 300px)',
  ads_height: 'Height (e.g. 250px)',
  confirm_delete_ad: 'Delete this ad?',
  users_count_label: 'users',
  users_no_users: 'No users',
  users_registered_at: 'Date',
  req_months: 'month',
  tab_notifications: 'Notifications',
  notif_title: 'Send Notification',
  notif_message_pl: 'Write the message...',
  notif_target_all: 'All users',
  notif_target_specific: 'Specific user',
  notif_send: 'Send Notification',
  notif_sent: '✓ Sent',
  notif_no_notifs: 'No notifications',
  notif_history: 'Notification history',
  notif_email_pl: 'User email',
  notif_preview: 'Notification Preview',
  notif_sent_at: 'Sent',
  notif_schedule_label: 'Schedule (specific time)',
  notif_scheduled_time: 'Scheduled at',
  notif_pending: 'Pending',
}

const dict = { ar, en }

export const LangContext = createContext()

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem(STORAGE_KEY) || 'ar' } catch { return 'ar' }
  })

  useEffect(() => {
    try { localStorage.setItem(STORAGE_KEY, lang) } catch {}
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
  }, [lang])

  const t = (key, vars = {}) => {
    let val = dict[lang]?.[key] || dict.ar[key] || key
    for (const [k, v] of Object.entries(vars)) {
      val = val.replace(`{${k}}`, v)
    }
    return val
  }

  const toggleLang = () => setLang(l => l === 'ar' ? 'en' : 'ar')

  return (
    <LangContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
